version: '3'

services:
  web: 
    container_name: murdermysteryapp_backend
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    links:
      - db

  frontend:
    container_name: murdermysteryapp-frontend
    restart: always
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true
    
  db:
    container_name: murdermysteryapp_db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=murdermysteryapp
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=root
    volumes:
      - ./data-db:/var/lib/mysql
volumes:
  db-data: {}

