# build step
FROM node:16-alpine as build

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json .

RUN npm install

COPY . .

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

RUN mkdir -p node_modules/.vite && chmod -R 777 node_modules/.vite

RUN npm run build

FROM nginx:1.15

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

COPY --from=build  /usr/src/app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
