version: '3'

services:
  web: 
    container_name: murdermysteryapp_backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    links:
      - db
  db:
    container_name: murdermysteryapp_db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=murdermysteryapp
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=root
    volumes:
      - ./data-db:/var/lib/mysql
volumes:
  db-data: {}

